import { canonicalNseSymbolBase } from './symbolCrossref';

export const INDUSTRY_MAP: Record<string, string> = {
  '360ONE': 'Financial Services',
  '3MINDIA': 'Diversified',
  'AADHARHFC': 'Financial Services',
  'AARTIDRUGS': 'Healthcare',
  'AARTIIND': 'Chemicals',
  'AARTIPHARM': 'Healthcare',
  'AAVAS': 'Financial Services',
  'ABB': 'Capital Goods',
  'ABBOTINDIA': 'Healthcare',
  'ABCAPITAL': 'Financial Services',
  'ABDL': 'Fast Moving Consumer Goods',
  'ABFRL': 'Consumer Services',
  'ABLBL': 'Consumer Services',
  'ABREL': 'Realty',
  'ABSLAMC': 'Financial Services',
  'ACC': 'Construction Materials',
  'ACE': 'Capital Goods',
  'ACI': 'Chemicals',
  'ACMESOLAR': 'Power',
  'ACUTAAS': 'Healthcare',
  'ADANIENSOL': 'Power',
  'ADANIENT': 'Metals & Mining',
  'ADANIGREEN': 'Power',
  'ADANIPORTS': 'Services',
  'ADANIPOWER': 'Power',
  'ADVENZYMES': 'Healthcare',
  'AEGISLOG': 'Oil Gas & Consumable Fuels',
  'AEGISVOPAK': 'Oil Gas & Consumable Fuels',
  'AETHER': 'Chemicals',
  'AFCONS': 'Construction',
  'AFFLE': 'Information Technology',
  'AGI': 'Capital Goods',
  'AHLUCONT': 'Construction',
  'AIAENG': 'Capital Goods',
  'AIIL': 'Financial Services',
  'AJANTPHARM': 'Healthcare',
  'AKUMS': 'Healthcare',
  'AKZOINDIA': 'Consumer Durables',
  'ALIVUS': 'Healthcare',
  'ALKEM': 'Healthcare',
  'ALKYLAMINE': 'Chemicals',
  'ALLCARGO': 'Services',
  'ALOKINDS': 'Textiles',
  'AMBER': 'Consumer Durables',
  'AMBUJACEM': 'Construction Materials',
  'AMIORG': 'Healthcare',
  'ANANDRATHI': 'Financial Services',
  'ANANTRAJ': 'Realty',
  'ANGELONE': 'Financial Services',
  'ANTHEM': 'Healthcare',
  'ANURAS': 'Chemicals',
  'APARINDS': 'Capital Goods',
  'APLAPOLLO': 'Capital Goods',
  'APLLTD': 'Healthcare',
  'APOLLOHOSP': 'Healthcare',
  'APOLLOTYRE': 'Automobile and Auto Components',
  'APTUS': 'Financial Services',
  'ARE&M': 'Automobile and Auto Components',
  'ARVIND': 'Textiles',
  'ARVINDFASN': 'Consumer Services',
  'ASAHIINDIA': 'Automobile and Auto Components',
  'ASHOKA': 'Construction',
  'ASHOKLEY': 'Capital Goods',
  'ASIANPAINT': 'Consumer Durables',
  'ASKAUTOLTD': 'Automobile and Auto Components',
  'ASTERDM': 'Healthcare',
  'ASTRAL': 'Capital Goods',
  'ASTRAMICRO': 'Capital Goods',
  'ASTRAZEN': 'Healthcare',
  'ATGL': 'Oil Gas & Consumable Fuels',
  'ATHERENERG': 'Automobile and Auto Components',
  'ATUL': 'Chemicals',
  'AUBANK': 'Financial Services',
  'AUROPHARMA': 'Healthcare',
  'AVALON': 'Capital Goods',
  'AVANTIFEED': 'Fast Moving Consumer Goods',
  'AWL': 'Fast Moving Consumer Goods',
  'AXISBANK': 'Financial Services',
  'AZAD': 'Capital Goods',
  'BAJAJ-AUTO': 'Automobile and Auto Components',
  'BAJAJCON': 'Fast Moving Consumer Goods',
  'BAJAJELEC': 'Consumer Durables',
  'BAJAJFINSV': 'Financial Services',
  'BAJAJHFL': 'Financial Services',
  'BAJAJHIND': 'Fast Moving Consumer Goods',
  'BAJAJHLDNG': 'Financial Services',
  'BAJFINANCE': 'Financial Services',
  'BALAMINES': 'Chemicals',
  'BALKRISIND': 'Automobile and Auto Components',
  'BALMLAWRIE': 'Diversified',
  'BALRAMCHIN': 'Fast Moving Consumer Goods',
  'BANCOINDIA': 'Automobile and Auto Components',
  'BANDHANBNK': 'Financial Services',
  'BANKBARODA': 'Financial Services',
  'BANKINDIA': 'Financial Services',
  'BASF': 'Chemicals',
  'BATAINDIA': 'Consumer Durables',
  'BAYERCROP': 'Chemicals',
  'BBL': 'Capital Goods',
  'BBTC': 'Fast Moving Consumer Goods',
  'BDL': 'Capital Goods',
  'BECTORFOOD': 'Fast Moving Consumer Goods',
  'BEL': 'Capital Goods',
  'BELRISE': 'Automobile and Auto Components',
  'BEML': 'Capital Goods',
  'BEPL': 'Chemicals',
  'BERGEPAINT': 'Consumer Durables',
  'BHARATFORG': 'Automobile and Auto Components',
  'BHARTIARTL': 'Telecommunication',
  'BHARTIHEXA': 'Telecommunication',
  'BHEL': 'Capital Goods',
  'BIKAJI': 'Fast Moving Consumer Goods',
  'BIOCON': 'Healthcare',
  'BIRLACORPN': 'Construction Materials',
  'BLS': 'Consumer Services',
  'BLUEDART': 'Services',
  'BLUEJET': 'Healthcare',
  'BLUESTARCO': 'Consumer Durables',
  'BOMDYEING': 'Textiles',
  'BOROLTD': 'Consumer Durables',
  'BORORENEW': 'Capital Goods',
  'BOSCHLTD': 'Automobile and Auto Components',
  'BPCL': 'Oil Gas & Consumable Fuels',
  'BRIGADE': 'Realty',
  'BRITANNIA': 'Fast Moving Consumer Goods',
  'BSE': 'Financial Services',
  'BSOFT': 'Information Technology',
  'CAMPUS': 'Consumer Durables',
  'CAMS': 'Financial Services',
  'CANBK': 'Financial Services',
  'CANFINHOME': 'Financial Services',
  'CANHLIFE': 'Financial Services',
  'CAPLIPOINT': 'Healthcare',
  'CARBORUNIV': 'Capital Goods',
  'CARTRADE': 'Consumer Services',
  'CASTROLIND': 'Oil Gas & Consumable Fuels',
  'CCL': 'Fast Moving Consumer Goods',
  'CDSL': 'Financial Services',
  'CEATLTD': 'Automobile and Auto Components',
  'CELLO': 'Consumer Durables',
  'CEMPRO': 'Construction',
  'CENTRALBK': 'Financial Services',
  'CENTURYPLY': 'Consumer Durables',
  'CERA': 'Consumer Durables',
  'CESC': 'Power',
  'CGCL': 'Financial Services',
  'CGPOWER': 'Capital Goods',
  'CHALET': 'Consumer Services',
  'CHAMBLFERT': 'Chemicals',
  'CHEMPLASTS': 'Chemicals',
  'CHENNPETRO': 'Oil Gas & Consumable Fuels',
  'CHOICEIN': 'Financial Services',
  'CHOLAFIN': 'Financial Services',
  'CHOLAHLDNG': 'Financial Services',
  'CIEINDIA': 'Automobile and Auto Components',
  'CIGNITITEC': 'Information Technology',
  'CIPLA': 'Healthcare',
  'CLEAN': 'Chemicals',
  'CMSINFO': 'Services',
  'COALINDIA': 'Oil Gas & Consumable Fuels',
  'COCHINSHIP': 'Capital Goods',
  'COFORGE': 'Information Technology',
  'COHANCE': 'Healthcare',
  'COLPAL': 'Fast Moving Consumer Goods',
  'CONCOR': 'Services',
  'CONCORDBIO': 'Healthcare',
  'CONFIPET': 'Oil Gas & Consumable Fuels',
  'COROMANDEL': 'Chemicals',
  'CPPLUS': 'Capital Goods',
  'CRAFTSMAN': 'Automobile and Auto Components',
  'CREDITACC': 'Financial Services',
  'CRISIL': 'Financial Services',
  'CROMPTON': 'Consumer Durables',
  'CSBBANK': 'Financial Services',
  'CUB': 'Financial Services',
  'CUMMINSIND': 'Capital Goods',
  'CYIENT': 'Information Technology',
  'CYIENTDLM': 'Capital Goods',
  'DABUR': 'Fast Moving Consumer Goods',
  'DALBHARAT': 'Construction Materials',
  'DATAMATICS': 'Information Technology',
  'DATAPATTNS': 'Capital Goods',
  'DBL': 'Construction',
  'DBREALTY': 'Realty',
  'DCAL': 'Healthcare',
  'DCBBANK': 'Financial Services',
  'DCMSHRIRAM': 'Diversified',
  'DCXINDIA': 'Capital Goods',
  'DEEPAKFERT': 'Chemicals',
  'DEEPAKNTR': 'Chemicals',
  'DELHIVERY': 'Services',
  'DELTACORP': 'Consumer Services',
  'DEN': 'Media Entertainment & Publication',
  'DEVYANI': 'Consumer Services',
  'DHANI': 'Financial Services',
  'DHANUKA': 'Chemicals',
  'DISHTV': 'Media Entertainment & Publication',
  'DIVISLAB': 'Healthcare',
  'DIXON': 'Consumer Durables',
  'DLF': 'Realty',
  'DMART': 'Consumer Services',
  'DODLA': 'Fast Moving Consumer Goods',
  'DOMS': 'Fast Moving Consumer Goods',
  'DREAMFOLKS': 'Services',
  'DRREDDY': 'Healthcare',
  'DYNAMATECH': 'Capital Goods',
  'EASEMYTRIP': 'Consumer Services',
  'ECLERX': 'Services',
  'EDELWEISS': 'Financial Services',
  'EICHERMOT': 'Automobile and Auto Components',
  'EIDPARRY': 'Fast Moving Consumer Goods',
  'EIHOTEL': 'Consumer Services',
  'ELECON': 'Capital Goods',
  'ELECTCAST': 'Capital Goods',
  'ELGIEQUIP': 'Capital Goods',
  'EMAMILTD': 'Fast Moving Consumer Goods',
  'EMBDL': 'Realty',
  'EMCURE': 'Healthcare',
  'EMIL': 'Consumer Services',
  'EMMVEE': 'Capital Goods',
  'EMUDHRA': 'Information Technology',
  'ENDURANCE': 'Automobile and Auto Components',
  'ENGINERSIN': 'Construction',
  'ENRIN': 'Capital Goods',
  'ENTERO': 'Consumer Services',
  'EPIGRAL': 'Chemicals',
  'EPL': 'Capital Goods',
  'EQUITASBNK': 'Financial Services',
  'ERIS': 'Healthcare',
  'ESAFSFB': 'Financial Services',
  'ESCORTS': 'Capital Goods',
  'ETERNAL': 'Consumer Services',
  'ETHOSLTD': 'Consumer Durables',
  'EVEREADY': 'Fast Moving Consumer Goods',
  'EXIDEIND': 'Automobile and Auto Components',
  'FACT': 'Chemicals',
  'FCL': 'Chemicals',
  'FDC': 'Healthcare',
  'FEDERALBNK': 'Financial Services',
  'FIEMIND': 'Automobile and Auto Components',
  'FINCABLES': 'Capital Goods',
  'FINEORG': 'Chemicals',
  'FINPIPE': 'Capital Goods',
  'FIRSTCRY': 'Consumer Services',
  'FIVESTAR': 'Financial Services',
  'FLUOROCHEM': 'Chemicals',
  'FORCEMOT': 'Automobile and Auto Components',
  'FORTIS': 'Healthcare',
  'FSL': 'Services',
  'FUSION': 'Financial Services',
  'GABRIEL': 'Automobile and Auto Components',
  'GAEL': 'Fast Moving Consumer Goods',
  'GAIL': 'Oil Gas & Consumable Fuels',
  'GALLANTT': 'Capital Goods',
  'GANESHHOUC': 'Realty',
  'GATEWAY': 'Services',
  'GESHIP': 'Services',
  'GHCL': 'Chemicals',
  'GICRE': 'Financial Services',
  'GILLETTE': 'Fast Moving Consumer Goods',
  'GLAND': 'Healthcare',
  'GLAXO': 'Healthcare',
  'GLENMARK': 'Healthcare',
  'GMDCLTD': 'Metals & Mining',
  'GMMPFAUDLR': 'Capital Goods',
  'GMRAIRPORT': 'Services',
  'GNFC': 'Chemicals',
  'GOCOLORS': 'Consumer Services',
  'GODFRYPHLP': 'Fast Moving Consumer Goods',
  'GODIGIT': 'Financial Services',
  'GODREJAGRO': 'Fast Moving Consumer Goods',
  'GODREJCP': 'Fast Moving Consumer Goods',
  'GODREJIND': 'Diversified',
  'GODREJPROP': 'Realty',
  'GOKEX': 'Textiles',
  'GOPAL': 'Fast Moving Consumer Goods',
  'GPIL': 'Capital Goods',
  'GPPL': 'Services',
  'GRANULES': 'Healthcare',
  'GRAPHITE': 'Capital Goods',
  'GRASIM': 'Construction Materials',
  'GRAVITA': 'Metals & Mining',
  'GREAVESCOT': 'Capital Goods',
  'GREENPANEL': 'Consumer Durables',
  'GREENPLY': 'Consumer Durables',
  'GRINDWELL': 'Capital Goods',
  'GRINFRA': 'Construction',
  'GROWW': 'Financial Services',
  'GRSE': 'Capital Goods',
  'GRWRHITECH': 'Capital Goods',
  'GSFC': 'Chemicals',
  'GSPL': 'Oil Gas & Consumable Fuels',
  'GUJALKALI': 'Chemicals',
  'GUJENERGY': 'Oil Gas & Consumable Fuels',
  'GULFOILLUB': 'Oil Gas & Consumable Fuels',
  'GVT&D': 'Capital Goods',
  'HAL': 'Capital Goods',
  'HAPPSTMNDS': 'Information Technology',
  'HAPPYFORGE': 'Capital Goods',
  'HARSHA': 'Capital Goods',
  'HATHWAY': 'Media Entertainment & Publication',
  'HAVELLS': 'Consumer Durables',
  'HBLENGINE': 'Capital Goods',
  'HCC': 'Construction',
  'HCG': 'Healthcare',
  'HCLTECH': 'Information Technology',
  'HDBFS': 'Financial Services',
  'HDFCAMC': 'Financial Services',
  'HDFCBANK': 'Financial Services',
  'HDFCLIFE': 'Financial Services',
  'HEG': 'Capital Goods',
  'HEIDELBERG': 'Construction Materials',
  'HEMIPROP': 'Services',
  'HERITGFOOD': 'Fast Moving Consumer Goods',
  'HEROMOTOCO': 'Automobile and Auto Components',
  'HEXT': 'Information Technology',
  'HFCL': 'Telecommunication',
  'HGINFRA': 'Construction',
  'HIKAL': 'Healthcare',
  'HINDALCO': 'Metals & Mining',
  'HINDCOPPER': 'Metals & Mining',
  'HINDOILEXP': 'Oil Gas & Consumable Fuels',
  'HINDPETRO': 'Oil Gas & Consumable Fuels',
  'HINDUNILVR': 'Fast Moving Consumer Goods',
  'HINDWAREAP': 'Consumer Durables',
  'HINDZINC': 'Metals & Mining',
  'HNDFDS': 'Fast Moving Consumer Goods',
  'HOMEFIRST': 'Financial Services',
  'HONASA': 'Fast Moving Consumer Goods',
  'HONAUT': 'Capital Goods',
  'HSCL': 'Chemicals',
  'HUDCO': 'Financial Services',
  'HYUNDAI': 'Automobile and Auto Components',
  'ICICIAMC': 'Financial Services',
  'ICICIBANK': 'Financial Services',
  'ICICIGI': 'Financial Services',
  'ICICIPRULI': 'Financial Services',
  'ICIL': 'Textiles',
  'IDBI': 'Financial Services',
  'IDEA': 'Telecommunication',
  'IDEAFORGE': 'Capital Goods',
  'IDFCFIRSTB': 'Financial Services',
  'IEX': 'Financial Services',
  'IFBIND': 'Consumer Durables',
  'IFCI': 'Financial Services',
  'IGIL': 'Services',
  'IGL': 'Oil Gas & Consumable Fuels',
  'IIFL': 'Financial Services',
  'IIFLCAPS': 'Financial Services',
  'IKS': 'Information Technology',
  'IMAGICAA': 'Consumer Services',
  'IMFA': 'Metals & Mining',
  'INDGN': 'Healthcare',
  'INDHOTEL': 'Consumer Services',
  'INDIACEM': 'Construction Materials',
  'INDIAGLYCO': 'Chemicals',
  'INDIAMART': 'Consumer Services',
  'INDIANB': 'Financial Services',
  'INDIASHLTR': 'Financial Services',
  'INDIGO': 'Services',
  'INDIGOPNTS': 'Consumer Durables',
  'INDUSINDBK': 'Financial Services',
  'INDUSTOWER': 'Telecommunication',
  'INFIBEAM': 'Financial Services',
  'INFY': 'Information Technology',
  'INGERRAND': 'Capital Goods',
  'INNOVACAP': 'Healthcare',
  'INOXGREEN': 'Utilities',
  'INOXINDIA': 'Capital Goods',
  'INOXWIND': 'Capital Goods',
  'INTELLECT': 'Information Technology',
  'IOB': 'Financial Services',
  'IOC': 'Oil Gas & Consumable Fuels',
  'IONEXCHANG': 'Utilities',
  'IPCALAB': 'Healthcare',
  'IPL': 'Chemicals',
  'IRB': 'Construction',
  'IRCON': 'Construction',
  'IRCTC': 'Consumer Services',
  'IREDA': 'Financial Services',
  'IRFC': 'Financial Services',
  'ISGEC': 'Construction',
  'ITC': 'Fast Moving Consumer Goods',
  'ITCHOTELS': 'Consumer Services',
  'ITDCEM': 'Construction',
  'ITI': 'Telecommunication',
  'IXIGO': 'Consumer Services',
  'J&KBANK': 'Financial Services',
  'JAIBALAJI': 'Metals & Mining',
  'JAICORPLTD': 'Capital Goods',
  'JAINREC': 'Metals & Mining',
  'JAMNAAUTO': 'Automobile and Auto Components',
  'JBCHEPHARM': 'Healthcare',
  'JBMA': 'Automobile and Auto Components',
  'JCHAC': 'Consumer Durables',
  'JINDALSAW': 'Capital Goods',
  'JINDALSTEL': 'Metals & Mining',
  'JINDWORLD': 'Textiles',
  'JIOFIN': 'Financial Services',
  'JISLJALEQS': 'Capital Goods',
  'JKCEMENT': 'Construction Materials',
  'JKIL': 'Construction',
  'JKLAKSHMI': 'Construction Materials',
  'JKPAPER': 'Forest Materials',
  'JKTYRE': 'Automobile and Auto Components',
  'JLHL': 'Healthcare',
  'JMFINANCIL': 'Financial Services',
  'JPPOWER': 'Power',
  'JSFB': 'Financial Services',
  'JSL': 'Metals & Mining',
  'JSWCEMENT': 'Construction Materials',
  'JSWENERGY': 'Power',
  'JSWINFRA': 'Services',
  'JSWSTEEL': 'Metals & Mining',
  'JTEKTINDIA': 'Automobile and Auto Components',
  'JTLIND': 'Capital Goods',
  'JUBLFOOD': 'Consumer Services',
  'JUBLINGREA': 'Chemicals',
  'JUBLPHARMA': 'Healthcare',
  'JUNIPER': 'Consumer Services',
  'JUSTDIAL': 'Consumer Services',
  'JWL': 'Capital Goods',
  'JYOTHYLAB': 'Fast Moving Consumer Goods',
  'JYOTICNC': 'Capital Goods',
  'KAJARIACER': 'Consumer Durables',
  'KALAMANDIR': 'Consumer Services',
  'KALYANKJIL': 'Consumer Durables',
  'KANSAINER': 'Consumer Durables',
  'KARURVYSYA': 'Financial Services',
  'KAYNES': 'Capital Goods',
  'KEC': 'Construction',
  'KEI': 'Capital Goods',
  'KFINTECH': 'Financial Services',
  'KIMS': 'Healthcare',
  'KIRLOSBROS': 'Capital Goods',
  'KIRLOSENG': 'Capital Goods',
  'KIRLPNU': 'Capital Goods',
  'KNRCON': 'Construction',
  'KOLTEPATIL': 'Realty',
  'KOTAKBANK': 'Financial Services',
  'KPIL': 'Construction',
  'KPITTECH': 'Information Technology',
  'KPRMILL': 'Textiles',
  'KRBL': 'Fast Moving Consumer Goods',
  'KSB': 'Capital Goods',
  'KSCL': 'Fast Moving Consumer Goods',
  'KSL': 'Capital Goods',
  'KTKBANK': 'Financial Services',
  'LALPATHLAB': 'Healthcare',
  'LANDMARK': 'Automobile and Auto Components',
  'LATENTVIEW': 'Information Technology',
  'LAURUSLABS': 'Healthcare',
  'LEMONTREE': 'Consumer Services',
  'LENSKART': 'Consumer Services',
  'LGEINDIA': 'Consumer Durables',
  'LICHSGFIN': 'Financial Services',
  'LICI': 'Financial Services',
  'LINDEINDIA': 'Chemicals',
  'LLOYDSENGG': 'Capital Goods',
  'LLOYDSME': 'Metals & Mining',
  'LMW': 'Capital Goods',
  'LODHA': 'Realty',
  'LT': 'Construction',
  'LTF': 'Financial Services',
  'LTFOODS': 'Fast Moving Consumer Goods',
  'LTIM': 'Information Technology',
  'LTM': 'Information Technology',
  'LTTS': 'Information Technology',
  'LUPIN': 'Healthcare',
  'LUXIND': 'Textiles',
  'LXCHEM': 'Chemicals',
  'M&M': 'Automobile and Auto Components',
  'M&MFIN': 'Financial Services',
  'MAHABANK': 'Financial Services',
  'MAHLIFE': 'Realty',
  'MAHLOG': 'Services',
  'MAHSEAMLES': 'Capital Goods',
  'MAITHANALL': 'Metals & Mining',
  'MANAPPURAM': 'Financial Services',
  'MANINFRA': 'Construction',
  'MANKIND': 'Healthcare',
  'MANYAVAR': 'Consumer Services',
  'MAPMYINDIA': 'Information Technology',
  'MARICO': 'Fast Moving Consumer Goods',
  'MARKSANS': 'Healthcare',
  'MARUTI': 'Automobile and Auto Components',
  'MASTEK': 'Information Technology',
  'MAXHEALTH': 'Healthcare',
  'MAZDOCK': 'Capital Goods',
  'MCX': 'Financial Services',
  'MEDANTA': 'Healthcare',
  'MEDPLUS': 'Consumer Services',
  'MEESHO': 'Consumer Services',
  'METROBRAND': 'Consumer Durables',
  'METROPOLIS': 'Healthcare',
  'MFSL': 'Financial Services',
  'MGL': 'Oil Gas & Consumable Fuels',
  'MHRIL': 'Consumer Services',
  'MIDHANI': 'Capital Goods',
  'MINDACORP': 'Automobile and Auto Components',
  'MMTC': 'Services',
  'MOIL': 'Metals & Mining',
  'MOTHERSON': 'Automobile and Auto Components',
  'MOTILALOFS': 'Financial Services',
  'MPHASIS': 'Information Technology',
  'MRF': 'Automobile and Auto Components',
  'MRPL': 'Oil Gas & Consumable Fuels',
  'MSTCLTD': 'Services',
  'MSUMI': 'Automobile and Auto Components',
  'MTARTECH': 'Capital Goods',
  'MUTHOOTFIN': 'Financial Services',
  'MUTHOOTMF': 'Financial Services',
  'NAM-INDIA': 'Financial Services',
  'NATCOPHARM': 'Healthcare',
  'NATIONALUM': 'Metals & Mining',
  'NAUKRI': 'Consumer Services',
  'NAVA': 'Power',
  'NAVINFLUOR': 'Chemicals',
  'NAZARA': 'Media Entertainment & Publication',
  'NBCC': 'Construction',
  'NCC': 'Construction',
  'NEOGEN': 'Chemicals',
  'NESCO': 'Services',
  'NESTLEIND': 'Fast Moving Consumer Goods',
  'NETWEB': 'Information Technology',
  'NETWORK18': 'Media Entertainment & Publication',
  'NEULANDLAB': 'Healthcare',
  'NEWGEN': 'Information Technology',
  'NFL': 'Chemicals',
  'NH': 'Healthcare',
  'NHPC': 'Power',
  'NIACL': 'Financial Services',
  'NIITMTS': 'Consumer Services',
  'NIVABUPA': 'Financial Services',
  'NLCINDIA': 'Power',
  'NMDC': 'Metals & Mining',
  'NOCIL': 'Chemicals',
  'NRBBEARING': 'Automobile and Auto Components',
  'NSLNISP': 'Metals & Mining',
  'NTPC': 'Power',
  'NTPCGREEN': 'Power',
  'NUVAMA': 'Financial Services',
  'NUVOCO': 'Construction Materials',
  'NYKAA': 'Consumer Services',
  'OBEROIRLTY': 'Realty',
  'OFSS': 'Information Technology',
  'OIL': 'Oil Gas & Consumable Fuels',
  'OLAELEC': 'Automobile and Auto Components',
  'OLECTRA': 'Automobile and Auto Components',
  'ONESOURCE': 'Healthcare',
  'ONGC': 'Oil Gas & Consumable Fuels',
  'OPTIEMUS': 'Telecommunication',
  'ORCHPHARMA': 'Healthcare',
  'ORIENTCEM': 'Construction Materials',
  'ORIENTELEC': 'Consumer Durables',
  'ORISSAMINE': 'Metals & Mining',
  'PAGEIND': 'Textiles',
  'PAISALO': 'Financial Services',
  'PARADEEP': 'Chemicals',
  'PARAS': 'Capital Goods',
  'PARKHOTELS': 'Consumer Services',
  'PATANJALI': 'Fast Moving Consumer Goods',
  'PATELENG': 'Construction',
  'PAYTM': 'Financial Services',
  'PCBL': 'Chemicals',
  'PEL': 'Financial Services',
  'PERSISTENT': 'Information Technology',
  'PETRONET': 'Oil Gas & Consumable Fuels',
  'PFC': 'Financial Services',
  'PFIZER': 'Healthcare',
  'PGEL': 'Consumer Durables',
  'PGHH': 'Fast Moving Consumer Goods',
  'PGHL': 'Healthcare',
  'PHOENIXLTD': 'Realty',
  'PIDILITIND': 'Chemicals',
  'PIIND': 'Chemicals',
  'PINELABS': 'Financial Services',
  'PIRAMALFIN': 'Financial Services',
  'PNB': 'Financial Services',
  'PNBHOUSING': 'Financial Services',
  'PNCINFRA': 'Construction',
  'POLICYBZR': 'Financial Services',
  'POLYCAB': 'Capital Goods',
  'POLYMED': 'Healthcare',
  'POLYPLEX': 'Capital Goods',
  'POONAWALLA': 'Financial Services',
  'POWERGRID': 'Power',
  'POWERINDIA': 'Capital Goods',
  'POWERMECH': 'Construction',
  'PPLPHARMA': 'Healthcare',
  'PRAJIND': 'Capital Goods',
  'PREMIERENE': 'Capital Goods',
  'PRESTIGE': 'Realty',
  'PRICOLLTD': 'Automobile and Auto Components',
  'PRINCEPIPE': 'Capital Goods',
  'PRUDENT': 'Financial Services',
  'PTC': 'Power',
  'PTCIL': 'Capital Goods',
  'PURVA': 'Realty',
  'PVRINOX': 'Media Entertainment & Publication',
  'PWL': 'Consumer Services',
  'QUESS': 'Services',
  'RADICO': 'Fast Moving Consumer Goods',
  'RAILTEL': 'Telecommunication',
  'RAIN': 'Chemicals',
  'RAINBOW': 'Healthcare',
  'RAJESHEXPO': 'Consumer Durables',
  'RALLIS': 'Chemicals',
  'RAMCOCEM': 'Construction Materials',
  'RAMKY': 'Construction',
  'RATEGAIN': 'Information Technology',
  'RATNAMANI': 'Capital Goods',
  'RAYMOND': 'Realty',
  'RAYMONDLSL': 'Textiles',
  'RBA': 'Consumer Services',
  'RBLBANK': 'Financial Services',
  'RCF': 'Chemicals',
  'RECLTD': 'Financial Services',
  'REDINGTON': 'Services',
  'REDTAPE': 'Consumer Durables',
  'RELIANCE': 'Oil Gas & Consumable Fuels',
  'RELIGARE': 'Financial Services',
  'RELINFRA': 'Power',
  'RENUKA': 'Fast Moving Consumer Goods',
  'RESPONIND': 'Consumer Durables',
  'RHIM': 'Capital Goods',
  'RITES': 'Construction',
  'RKFORGE': 'Automobile and Auto Components',
  'ROLEXRINGS': 'Automobile and Auto Components',
  'ROSSARI': 'Chemicals',
  'ROUTE': 'Telecommunication',
  'RPOWER': 'Power',
  'RRKABEL': 'Capital Goods',
  'RTNINDIA': 'Consumer Services',
  'RVNL': 'Construction',
  'SAFARI': 'Consumer Durables',
  'SAGILITY': 'Information Technology',
  'SAIL': 'Metals & Mining',
  'SAILIFE': 'Healthcare',
  'SAMHI': 'Consumer Services',
  'SAMMAANCAP': 'Financial Services',
  'SANDUMA': 'Oil Gas & Consumable Fuels',
  'SANGHIIND': 'Construction Materials',
  'SANGHVIMOV': 'Capital Goods',
  'SANOFI': 'Healthcare',
  'SANSERA': 'Automobile and Auto Components',
  'SAPPHIRE': 'Consumer Services',
  'SARDAEN': 'Metals & Mining',
  'SAREGAMA': 'Media Entertainment & Publication',
  'SBCL': 'Capital Goods',
  'SBFC': 'Financial Services',
  'SBICARD': 'Financial Services',
  'SBILIFE': 'Financial Services',
  'SBIN': 'Financial Services',
  'SCHAEFFLER': 'Automobile and Auto Components',
  'SCHNEIDER': 'Capital Goods',
  'SCI': 'Services',
  'SENCO': 'Consumer Durables',
  'SEQUENT': 'Healthcare',
  'SFL': 'Consumer Durables',
  'SHARDAMOTR': 'Automobile and Auto Components',
  'SHAREINDIA': 'Financial Services',
  'SHILPAMED': 'Healthcare',
  'SHREECEM': 'Construction Materials',
  'SHRIPISTON': 'Automobile and Auto Components',
  'SHRIRAMFIN': 'Financial Services',
  'SHYAMMETL': 'Capital Goods',
  'SIEMENS': 'Capital Goods',
  'SIGNATURE': 'Realty',
  'SINDHUTRAD': 'Diversified',
  'SJVN': 'Power',
  'SKFINDIA': 'Capital Goods',
  'SOBHA': 'Realty',
  'SOLARINDS': 'Chemicals',
  'SONACOMS': 'Automobile and Auto Components',
  'SONATSOFTW': 'Information Technology',
  'SOUTHBANK': 'Financial Services',
  'SPANDANA': 'Financial Services',
  'SPARC': 'Healthcare',
  'SPLPETRO': 'Chemicals',
  'SRF': 'Chemicals',
  'SSWL': 'Automobile and Auto Components',
  'STAR': 'Healthcare',
  'STARCEMENT': 'Construction Materials',
  'STARHEALTH': 'Financial Services',
  'STLTECH': 'Telecommunication',
  'STYLAMIND': 'Consumer Durables',
  'SUBROS': 'Automobile and Auto Components',
  'SUDARSCHEM': 'Chemicals',
  'SULA': 'Fast Moving Consumer Goods',
  'SUMICHEM': 'Chemicals',
  'SUNDARMFIN': 'Financial Services',
  'SUNDRMFAST': 'Automobile and Auto Components',
  'SUNFLAG': 'Metals & Mining',
  'SUNPHARMA': 'Healthcare',
  'SUNTECK': 'Realty',
  'SUNTV': 'Media Entertainment & Publication',
  'SUPRAJIT': 'Automobile and Auto Components',
  'SUPREMEIND': 'Capital Goods',
  'SUPRIYA': 'Healthcare',
  'SURYAROSNI': 'Capital Goods',
  'SUVENPHAR': 'Healthcare',
  'SUZLON': 'Capital Goods',
  'SWANCORP': 'Chemicals',
  'SWANENERGY': 'Diversified',
  'SWIGGY': 'Consumer Services',
  'SWSOLAR': 'Construction',
  'SYMPHONY': 'Consumer Durables',
  'SYNGENE': 'Healthcare',
  'SYRMA': 'Capital Goods',
  'TANLA': 'Information Technology',
  'TARC': 'Realty',
  'TARIL': 'Capital Goods',
  'TATACAP': 'Financial Services',
  'TATACHEM': 'Chemicals',
  'TATACOMM': 'Telecommunication',
  'TATACONSUM': 'Fast Moving Consumer Goods',
  'TATAELXSI': 'Information Technology',
  'TATAINVEST': 'Financial Services',
  'TATAMOTORS': 'Automobile and Auto Components',
  'TATAPOWER': 'Power',
  'TATASTEEL': 'Metals & Mining',
  'TATATECH': 'Information Technology',
  'TBOTEK': 'Consumer Services',
  'TCIEXP': 'Services',
  'TCS': 'Information Technology',
  'TDPOWERSYS': 'Capital Goods',
  'TEAMLEASE': 'Services',
  'TECHM': 'Information Technology',
  'TECHNOE': 'Construction',
  'TEGA': 'Capital Goods',
  'TEJASNET': 'Telecommunication',
  'TENNIND': 'Automobile and Auto Components',
  'TEXRAIL': 'Capital Goods',
  'THELEELA': 'Consumer Services',
  'THERMAX': 'Capital Goods',
  'THOMASCOOK': 'Consumer Services',
  'TI': 'Fast Moving Consumer Goods',
  'TIIL': 'Capital Goods',
  'TIINDIA': 'Automobile and Auto Components',
  'TIMETECHNO': 'Capital Goods',
  'TIMKEN': 'Capital Goods',
  'TIPSMUSIC': 'Media Entertainment & Publication',
  'TIRUMALCHM': 'Chemicals',
  'TITAGARH': 'Capital Goods',
  'TITAN': 'Consumer Durables',
  'TMCV': 'Capital Goods',
  'TMPV': 'Automobile and Auto Components',
  'TORNTPHARM': 'Healthcare',
  'TORNTPOWER': 'Power',
  'TRAVELFOOD': 'Consumer Services',
  'TRENT': 'Consumer Services',
  'TRIDENT': 'Textiles',
  'TRITURBINE': 'Capital Goods',
  'TRIVENI': 'Fast Moving Consumer Goods',
  'TTML': 'Telecommunication',
  'TVSMOTOR': 'Automobile and Auto Components',
  'TVSSCS': 'Services',
  'UBL': 'Fast Moving Consumer Goods',
  'UCOBANK': 'Financial Services',
  'UJJIVANSFB': 'Financial Services',
  'ULTRACEMCO': 'Construction Materials',
  'UNIONBANK': 'Financial Services',
  'UNITDSPR': 'Fast Moving Consumer Goods',
  'UNOMINDA': 'Automobile and Auto Components',
  'UPL': 'Chemicals',
  'URBANCO': 'Consumer Services',
  'USHAMART': 'Capital Goods',
  'UTIAMC': 'Financial Services',
  'UTKARSHBNK': 'Financial Services',
  'VAIBHAVGBL': 'Consumer Durables',
  'VARROC': 'Automobile and Auto Components',
  'VBL': 'Fast Moving Consumer Goods',
  'VEDL': 'Metals & Mining',
  'VEEDOL': 'Oil Gas & Consumable Fuels',
  'VENKEYS': 'Fast Moving Consumer Goods',
  'VENUSPIPES': 'Capital Goods',
  'VESUVIUS': 'Capital Goods',
  'VGUARD': 'Consumer Durables',
  'VIJAYA': 'Healthcare',
  'VINATIORGA': 'Chemicals',
  'VIPIND': 'Consumer Durables',
  'VMART': 'Consumer Services',
  'VMM': 'Consumer Services',
  'VOLTAMP': 'Capital Goods',
  'VOLTAS': 'Consumer Durables',
  'VSTIND': 'Fast Moving Consumer Goods',
  'VTL': 'Textiles',
  'WAAREEENER': 'Capital Goods',
  'WABAG': 'Utilities',
  'WELCORP': 'Capital Goods',
  'WELENT': 'Construction',
  'WELSPUNLIV': 'Textiles',
  'WESTLIFE': 'Consumer Services',
  'WHIRLPOOL': 'Consumer Durables',
  'WIPRO': 'Information Technology',
  'WOCKPHARMA': 'Healthcare',
  'WONDERLA': 'Consumer Services',
  'WSTCSTPAPR': 'Forest Materials',
  'YATHARTH': 'Healthcare',
  'YESBANK': 'Financial Services',
  'ZEEL': 'Media Entertainment & Publication',
  'ZENSARTECH': 'Information Technology',
  'ZENTEC': 'Capital Goods',
  'ZFCVINDIA': 'Automobile and Auto Components',
  'ZOMATO': 'Consumer Services',
  'ZYDUSLIFE': 'Healthcare',
  'ZYDUSWELL': 'Fast Moving Consumer Goods',
};

const SHORT: Record<string, string> = {
  'Financial Services': 'FIN', 'Capital Goods': 'CAP', 'Healthcare': 'HC',
  'Information Technology': 'IT', 'Automobile and Auto Components': 'AUTO',
  'Oil Gas & Consumable Fuels': 'O&G', 'Metals & Mining': 'MTL',
  'Consumer Services': 'SVC', 'Construction Materials': 'MAT',
  'Fast Moving Consumer Goods': 'FMCG', 'Power': 'PWR', 'Chemicals': 'CHM',
  'Realty': 'RLT', 'Consumer Durables': 'DUR', 'Telecommunication': 'TEL',
  'Construction': 'CON', 'Textiles': 'TEX', 'Media Entertainment & Publication': 'MED',
  'Forest Materials': 'FRM', 'Diversified': 'DIV', 'Services': 'SVC',
  'Fertilizers & Agrochemicals': 'AGR',
};

export function getIndustryTag(symbol: string): string {
  const clean = canonicalNseSymbolBase(symbol);
  const ind = INDUSTRY_MAP[clean];
  if (!ind) return '';
  return SHORT[ind] ?? ind.slice(0, 3).toUpperCase();
}

export function getIndustryFull(symbol: string): string {
  const clean = canonicalNseSymbolBase(symbol);
  return INDUSTRY_MAP[clean] ?? '';
}
