const MAP: Record<string, string> = {
  // Automobiles & Components
  TATAMOTORS: 'AUTO', SHARDAMOTR: 'AUTO', SHRIPISTON: 'AUTO', GABRIEL: 'AUTO',
  RKFORGE: 'AUTO', MOTHERSON: 'AUTO', BALKRISIND: 'AUTO', APOLLOTYRE: 'AUTO',
  MARUTI: 'AUTO', MAHINDRA: 'AUTO', 'M&M': 'AUTO', 'BAJAJ-AUTO': 'AUTO',
  HEROMOTOCO: 'AUTO', EICHERMOT: 'AUTO', TVSMOTOR: 'AUTO', BOSCHLTD: 'AUTO',
  EXIDEIND: 'AUTO', AMARAJABAT: 'AUTO', SUNDRMFAST: 'AUTO', LUMAXTECH: 'AUTO',
  SUPRAJIT: 'AUTO', WABCO: 'AUTO', SUBROS: 'AUTO', CRAFTSMAN: 'AUTO',
  ENDURANCE: 'AUTO', ESCORTS: 'AUTO', TIINDIA: 'AUTO', MINDACORP: 'AUTO',
  MAHSCOOTER: 'AUTO', MINDA: 'AUTO', UNO: 'AUTO', AUTOAXLES: 'AUTO',
  JMNL: 'AUTO', SETCO: 'AUTO',

  // Banking Private
  HDFCBANK: 'BNK-PVT', ICICIBANK: 'BNK-PVT', AXISBANK: 'BNK-PVT',
  KOTAKBANK: 'BNK-PVT', INDUSINDBK: 'BNK-PVT', FEDERALBNK: 'BNK-PVT',
  EQUITASBNK: 'BNK-PVT', CUB: 'BNK-PVT', RBLBANK: 'BNK-PVT',
  IDFCFIRSTB: 'BNK-PVT', BANDHANBNK: 'BNK-PVT', DCBBANK: 'BNK-PVT',
  KTKBANK: 'BNK-PVT', SOUTHBANK: 'BNK-PVT', CSBBANK: 'BNK-PVT',
  UJJIVANSFB: 'BNK-PVT', FINOPB: 'BNK-PVT', SURYODAY: 'BNK-PVT',
  ESAFSFB: 'BNK-PVT', NAINITAL: 'BNK-PVT', TMVFINANCE: 'BNK-PVT',
  CITYUNIONBANK: 'BNK-PVT',

  // Banking PSU
  SBIN: 'BNK-PSU', PNB: 'BNK-PSU', BANKBARODA: 'BNK-PSU', CANBK: 'BNK-PSU',
  UNIONBANK: 'BNK-PSU', IOB: 'BNK-PSU', BANKINDIA: 'BNK-PSU',
  INDIANB: 'BNK-PSU', CENTRALBK: 'BNK-PSU', MAHABANK: 'BNK-PSU',
  UCO: 'BNK-PSU', PSB: 'BNK-PSU',

  // Chemicals
  APCOTEXIND: 'CHEM', FILATEX: 'CHEM', KANORICHEM: 'CHEM', VINTALABS: 'CHEM',
  TIRUPATIFL: 'CHEM', RAIN: 'CHEM', PIDILITIND: 'CHEM', DEEPAKNITR: 'CHEM',
  ATUL: 'CHEM', FINEORG: 'CHEM', GALAXYSURF: 'CHEM', NAVINFLUOR: 'CHEM',
  SUDARSCHEM: 'CHEM', TATACHEM: 'CHEM', CLEAN: 'CHEM', NOCIL: 'CHEM',
  PCBL: 'CHEM', INDIGOPNTS: 'CHEM', AKZOINDIA: 'CHEM', BASF: 'CHEM',
  GHCL: 'CHEM', GNFC: 'CHEM', GSFC: 'CHEM', GUJALKALI: 'CHEM',
  HIMADRI: 'CHEM', LXCHEM: 'CHEM', NEOGEN: 'CHEM', ROSSARI: 'CHEM',
  SRF: 'CHEM', VINATIORGA: 'CHEM', VIMTALABS: 'CHEM', BAYERCROPS: 'CHEM',
  GUJFLUORO: 'CHEM', FLUOROCHEM: 'CHEM', TATVA: 'CHEM', ANUPAM: 'CHEM',
  CHEMPLASTS: 'CHEM', DCMSHRIRAM: 'CHEM', EIDPARRY: 'CHEM',
  ORIENTBELL: 'CHEM', ALKYLAMINE: 'CHEM', BALMLAWRIE: 'CHEM',
  HERANBA: 'CHEM', INRAINBOW: 'CHEM', JUBLINGREA: 'CHEM',
  NUVAMA: 'CHEM', PAUSHAKLTD: 'CHEM', STERLINBIO: 'CHEM',
  TRANSPEK: 'CHEM', VINDHYATEL: 'CHEM', SPECIALITY: 'CHEM',

  // IT / Technology
  TCS: 'IT', INFY: 'IT', WIPRO: 'IT', HCLTECH: 'IT', TECHM: 'IT',
  MPHASIS: 'IT', LTIM: 'IT', PERSISTENT: 'IT', COFORGE: 'IT',
  MPSLTD: 'IT', E2E: 'IT', PFOCUS: 'IT', KPIT: 'IT', MASTEK: 'IT',
  NIIT: 'IT', TANLA: 'IT', ZENSARTECH: 'IT', CYIENT: 'IT',
  NEWGEN: 'IT', HAPPYFORGE: 'IT', TRIGYN: 'IT', ZENSAR: 'IT',
  RAMSYSCORP: 'IT', TATA_ELXSI: 'IT', TATAELXSI: 'IT',
  BIRLASOFT: 'IT', INTELLECT: 'IT', ECLERX: 'IT', FIRSTSOURCE: 'IT',
  SAKSOFT: 'IT', SUBEXLTD: 'IT', HINDWRATIO: 'IT', CMSINFO: 'IT',
  NAUKRI: 'IT', JUSTDIAL: 'IT', INDIAMART: 'IT', CARTRADE: 'IT',
  IRISINFOTECH: 'IT', IRISBUSNS: 'IT', IRISDOREME: 'IT', FSL: 'IT',

  // Pharma
  GUFICBIO: 'PHARMA', SUNPHARMA: 'PHARMA', DRREDDY: 'PHARMA',
  CIPLA: 'PHARMA', DIVISLAB: 'PHARMA', BIOCON: 'PHARMA', LUPIN: 'PHARMA',
  AUROPHARMA: 'PHARMA', GLAXO: 'PHARMA', PFIZER: 'PHARMA',
  ABBOTINDIA: 'PHARMA', SANOFI: 'PHARMA', ALKEM: 'PHARMA',
  TORNTPHARM: 'PHARMA', GRANULES: 'PHARMA', JBCHEPHARM: 'PHARMA',
  LAURUSLABS: 'PHARMA', MANKIND: 'PHARMA', NATCOPHARM: 'PHARMA',
  SUVEN: 'PHARMA', IOLCP: 'PHARMA', CAPLIPOINT: 'PHARMA',
  AJANTPHARM: 'PHARMA', IPCALAB: 'PHARMA', LAURUS: 'PHARMA',
  NEULANDLAB: 'PHARMA', SOLARA: 'PHARMA', STRIDES: 'PHARMA',
  GLAND: 'PHARMA', ZYDUSLIFE: 'PHARMA', SPARC: 'PHARMA',
  DIVIS: 'PHARMA', JB: 'PHARMA',

  // Real Estate
  ARKADE: 'REALTY', PROZONER: 'REALTY', DLF: 'REALTY', GODREJPROP: 'REALTY',
  PRESTIGE: 'REALTY', BRIGADE: 'REALTY', SOBHA: 'REALTY', MAHLIFE: 'REALTY',
  PHOENIXLTD: 'REALTY', SUNTECK: 'REALTY', KOLTEPATIL: 'REALTY',
  LODHA: 'REALTY', MACROTECH: 'REALTY', ANANTRAJ: 'REALTY',
  OMAXE: 'REALTY', RAYMOND: 'REALTY', ELDECO: 'REALTY',
  PURVA: 'REALTY', RUSTOMJEE: 'REALTY', KRISHNAFILM: 'REALTY',

  // Construction / Infrastructure
  UDS: 'INFRA', UNIVASTU: 'INFRA', NCC: 'INFRA', KNRCON: 'INFRA',
  PNCINFRA: 'INFRA', HGINFRA: 'INFRA', IRB: 'INFRA', SADBHAV: 'INFRA',
  GPPL: 'INFRA', ASHOKA: 'INFRA', GBINFRA: 'INFRA', JKIL: 'INFRA',
  HKINFRA: 'INFRA', PGHL: 'INFRA', PNC: 'INFRA', AHLEAST: 'INFRA',

  // Cement
  ULTRACEMCO: 'CEMENT', GRASIM: 'CEMENT', AMBUJACEM: 'CEMENT', ACC: 'CEMENT',
  SHREECEM: 'CEMENT', KCP: 'CEMENT', JKCEMENT: 'CEMENT',
  HEIDELBERG: 'CEMENT', INDIACEM: 'CEMENT', RAMCOCEM: 'CEMENT',
  DALMIA: 'CEMENT', NUVOCO: 'CEMENT', JKLAKSHMI: 'CEMENT',
  BIRLACORPN: 'CEMENT', STAR: 'CEMENT',

  // NBFC / Finance
  AAVAS: 'NBFC', CONSOFINVT: 'NBFC', PRUDENT: 'NBFC', BAJFINANCE: 'NBFC',
  BAJAJFINSV: 'NBFC', CHOLAFIN: 'NBFC', LICSGFIN: 'NBFC',
  MANAPPURAM: 'NBFC', MUTHOOTFIN: 'NBFC', PNBHOUSING: 'NBFC',
  REPCO: 'NBFC', SHRIRAMFIN: 'NBFC', CREDITACC: 'NBFC', IIFL: 'NBFC',
  'M&MFIN': 'NBFC', LTFH: 'NBFC', PIRAMALENT: 'NBFC', CHOICEIN: 'NBFC',
  MMFIN: 'NBFC', CAMS: 'NBFC', CDSL: 'NBFC', BSE: 'NBFC',
  MCX: 'NBFC', ANGELONE: 'NBFC', MOTILALOFS: 'NBFC',
  HDFCAMC: 'NBFC', NIPPBCF: 'NBFC', HOMEFIRST: 'NBFC', APTUS: 'NBFC',
  EDELWEISS: 'NBFC', MAHFIN: 'NBFC', SUNDARAM: 'NBFC',

  // Engineering / Capital Goods
  MENONBE: 'ENG', THEJO: 'ENG', CONTROLPR: 'ENG', BHEL: 'ENG',
  ABB: 'ENG', SIEMENS: 'ENG', AIAENG: 'ENG', CGPOWER: 'ENG',
  CUMMINSIND: 'ENG', KSB: 'ENG', THERMAX: 'ENG', VOLTAS: 'ENG',
  BLUESTAR: 'ENG', HAVELLS: 'ENG', POLYCAB: 'ENG', KEI: 'ENG',
  FINOLEX: 'ENG', ELGIEQUIP: 'ENG', GRINDWELL: 'ENG', KALYANKJIL: 'ENG',
  TRIVENI: 'ENG', BHELDEL: 'ENG', KECL: 'ENG', RIIL: 'ENG',
  PRAJ: 'ENG', TDPOWERSYS: 'ENG', GMRINFRA: 'ENG', ISGEC: 'ENG',
  LLOYDSME: 'ENG',

  // Media / Entertainment
  HMVL: 'MEDIA', ZEEL: 'MEDIA', SUNTV: 'MEDIA', PVRL: 'MEDIA',
  INOXLEISUR: 'MEDIA', JAGRAN: 'MEDIA', DBCORP: 'MEDIA',
  TVTODAY: 'MEDIA', NETWORK18: 'MEDIA', TV18BRDCST: 'MEDIA',
  NAUKRI: 'MEDIA', SAREGAMA: 'MEDIA', TIPS: 'MEDIA',

  // Packaging
  HUHTAMAKI: 'PACK', HUNTAMAKI: 'PACK', UFLEX: 'PACK', MOLD: 'PACK',
  TNPL: 'PACK', TIPSINDLTD: 'PACK', PARACABLES: 'PACK',
  EPL: 'PACK', POLYPLEX: 'PACK', ESTER: 'PACK', COSMOFILMS: 'PACK',

  // Healthcare Services / Diagnostics
  LALPATHLAB: 'DIAG', METROPOLIS: 'DIAG', THYROCARE: 'DIAG',
  APOLLOHOSP: 'HEALTH', FORTIS: 'HEALTH', NARAYNAHM: 'HEALTH',
  MAXHEALTH: 'HEALTH', ASTER: 'HEALTH', RAINBOW: 'HEALTH',
  VIJAYAHOSP: 'HEALTH', SHALBY: 'HEALTH', HCG: 'HEALTH',
  KRSNAA: 'DIAG', VIJAYA: 'DIAG', AGAPPE: 'DIAG',

  // Insurance
  STARHEALTH: 'INS', HDFCLIFE: 'INS', SBILIFE: 'INS',
  ICICIPRULI: 'INS', GICRE: 'INS', ICICIGI: 'INS', NIACL: 'INS',
  LIFINDIA: 'INS', BAJAJALLIANZ: 'INS', GODIGIT: 'INS',

  // Oil & Gas / Energy
  HINDPETRO: 'OIL', RELIANCE: 'OIL', BPCL: 'OIL', IOC: 'OIL',
  ONGC: 'OIL', GAIL: 'OIL', MGL: 'OIL', IGL: 'OIL',
  PETRONET: 'OIL', CASTROLIND: 'OIL', MRPL: 'OIL', CPCL: 'OIL',
  OIL: 'OIL', HPCL: 'OIL',

  // FMCG
  VENKEYS: 'FMCG', HINDUNILVR: 'FMCG', ITC: 'FMCG', NESTLEIND: 'FMCG',
  GODREJCP: 'FMCG', MARICO: 'FMCG', COLPAL: 'FMCG', DABUR: 'FMCG',
  EMAMILTD: 'FMCG', BRITANNIA: 'FMCG', VARUN: 'FMCG',
  TATACONSUM: 'FMCG', ZYDUSWELL: 'FMCG', JYOTHYLAB: 'FMCG',
  CCL: 'FMCG', BIKAJI: 'FMCG', DEVYANI: 'FMCG', WESTLIFE: 'FMCG',

  // Textiles
  SAPPHIRE: 'TEX', PAGEIND: 'TEX', ARVIND: 'TEX', TRIDENT: 'TEX',
  VARDHMAN: 'TEX', WELSPUNIND: 'TEX', KPRMILL: 'TEX', RSWM: 'TEX',
  SUTLEJTEX: 'TEX', NITIN: 'TEX', HIMATSEIDE: 'TEX', ALOKTEXT: 'TEX',

  // Services / HR / Staffing
  QUESS: 'SERV', TEAMLEASE: 'SERV', CARERATINGS: 'SERV',
  CRISIL: 'SERV', ICRA: 'SERV', INFOEDGE: 'SERV',

  // Defense / Aerospace
  DATAPATTNS: 'DEF', HAL: 'DEF', BEL: 'DEF', BEML: 'DEF',
  MAZDOCK: 'DEF', COCHINSHIP: 'DEF', GRSE: 'DEF', MIDHANI: 'DEF',
  DRAFTMASTER: 'DEF', PARAS: 'DEF', MTAR: 'DEF', SOLARIND: 'DEF',
  AVANTEL: 'DEF', ZEN: 'DEF', IDEAFORGE: 'DEF',

  // Metals / Mining
  TATASTEEL: 'METAL', HINDALCO: 'METAL', JSWSTEEL: 'METAL',
  SAIL: 'METAL', NMDC: 'METAL', HINDZINC: 'METAL', VEDL: 'METAL',
  JINDALSTEL: 'METAL', RATNAMANI: 'METAL', APL: 'METAL',
  APOLLOPIPE: 'METAL', LLOYDSENGG: 'METAL', WELCORP: 'METAL',
  JINDALSAW: 'METAL', HGCORP: 'METAL', MOIL: 'METAL',

  // Power / Utilities
  POWERGRID: 'POWER', NTPC: 'POWER', TATAPOWER: 'POWER',
  ADANIPOWER: 'POWER', CESC: 'POWER', TORNTPOWER: 'POWER',
  IREDA: 'POWER', INDIGRID: 'POWER', ADANIENT: 'POWER',
  JSHL: 'POWER', RATTAN: 'POWER', JPPOWER: 'POWER',

  // Building Materials
  CENTURYPLY: 'BUILD', GREENPANEL: 'BUILD', ASTERDM: 'BUILD',
  NEWATIA: 'BUILD', ASIANPAINT: 'BUILD', BERGER: 'BUILD',
  KANSAINER: 'BUILD', PIDILITE: 'BUILD', ITDCEM: 'BUILD',
  HALDYN: 'BUILD', CERA: 'BUILD', HSIL: 'BUILD',
  SUPRAJIT2: 'BUILD',
};

export function lookupSector(symbol: string): string {
  const clean = symbol.replace(/\.(NS|BO|BSE)$/i, '').toUpperCase();
  return MAP[clean] ?? '';
}
