// AUTO-GENERATED by scripts/run_survival_analysis.py — do not edit manually.
// Generated: 2026-08-07
// Kaplan-Meier probabilities of reaching the +5% target by day N, per archetype.

export interface SurvivalCurve {
  n: number;     // sample size
  n_hit: number; // events (reached 5%)
  median: number; // KM median days-to-5pct
  d5: number;     // P(hit by day 5)
  d10: number;    // P(hit by day 10)
  d20: number;    // P(hit by day 20)
}

export const SURVIVAL_CURVES: Record<string, SurvivalCurve> = {
  CompressionCoil: { n: 332, n_hit: 325, median: 1.0, d5: 0.9398, d10: 0.9518, d20: 0.9639 },
  MomentumPocket: { n: 313, n_hit: 308, median: 1.0, d5: 0.9425, d10: 0.9489, d20: 0.9521 },
  PerfectStorm: { n: 10, n_hit: 9, median: 1.0, d5: 0.9, d10: 0.9, d20: 0.9 },
  VolumeFootprint: { n: 13, n_hit: 13, median: 1.0, d5: 1.0, d10: 1.0, d20: 1.0 },
};
