/**
 * Survival inference — P(reach +5% by day N) per archetype.
 * Uses KM lookup from SURVIVAL_CURVES (auto-generated by run_survival_analysis.py).
 * Returns null when archetype is unknown.
 */

import { SURVIVAL_CURVES, SurvivalCurve } from './survivalCurves';

export interface SurvivalProb {
  d5: number;
  d10: number;
  d20: number;
  median: number;
  n: number;
}

export function getSurvivalProb(archetypeType: string | undefined): SurvivalProb | null {
  if (!archetypeType) return null;
  const curve: SurvivalCurve | undefined = SURVIVAL_CURVES[archetypeType];
  if (!curve) return null;
  return { d5: curve.d5, d10: curve.d10, d20: curve.d20, median: curve.median, n: curve.n };
}

/**
 * Returns a human-readable time-to-5% label for display in the screener,
 * e.g. "5d: 38% · 10d: 61%" when n ≥ 30, or "—" when no data.
 */
export function formatSurvivalLabel(archetypeType: string | undefined): string {
  const s = getSurvivalProb(archetypeType);
  if (!s || s.n < 20) return '—';
  return `5d: ${(s.d5 * 100).toFixed(0)}% · 10d: ${(s.d10 * 100).toFixed(0)}%`;
}
