// AUTO-GENERATED by scripts/run_survival_analysis.py -- do not edit manually.
// Generated: 2026-09-04
// Kaplan-Meier probabilities of reaching the +5% target by day N, per archetype.

export interface SurvivalCurve {
  n: number;     // sample size
  n_hit: number; // events (reached 5%)
  median: number; // KM median days-to-5pct
  d5: number;     // P(hit by day 5)
  d10: number;    // P(hit by day 10)
  d20: number;    // P(hit by day 20)
}

export const SURVIVAL_CURVES: Record<string, SurvivalCurve> = {
  CompressionCoil: { n: 130, n_hit: 127, median: 1.0, d5: 0.9641, d10: 0.9731, d20: 0.9731 },
  MomentumPocket: { n: 227, n_hit: 224, median: 1.0, d5: 0.9648, d10: 0.9736, d20: 0.9736 },
  VolumeFootprint: { n: 14, n_hit: 14, median: 1.0, d5: 0.9286, d10: 0.9286, d20: 0.9286 },
};
