// AUTO-GENERATED by scripts/run_survival_analysis.py — do not edit manually.
// Placeholder values — run the Python script after survival_times.csv is produced.
// Kaplan-Meier probabilities of reaching the +5% target by day N, per archetype.

export interface SurvivalCurve {
  n: number;      // sample size
  n_hit: number;  // events (reached 5%)
  median: number; // KM median days-to-5pct
  d5: number;     // P(hit by day 5)
  d10: number;    // P(hit by day 10)
  d20: number;    // P(hit by day 20)
}

// Placeholder priors from OOS backtest hit rates — updated by run_survival_analysis.py
export const SURVIVAL_CURVES: Record<string, SurvivalCurve> = {
  CompressionCoil: { n: 257, n_hit: 173, median: 12, d5: 0.28, d10: 0.48, d20: 0.67 },
  VolumeFootprint: { n: 62,  n_hit:  50, median:  9, d5: 0.38, d10: 0.61, d20: 0.78 },
  MomentumPocket:  { n: 39,  n_hit:  35, median:  7, d5: 0.45, d10: 0.68, d20: 0.83 },
  EMAStack:        { n: 32,  n_hit:  25, median: 10, d5: 0.34, d10: 0.55, d20: 0.72 },
  CircuitBreaker:  { n: 58,  n_hit:  45, median: 11, d5: 0.31, d10: 0.52, d20: 0.71 },
};
