// AUTO-GENERATED by scripts/train_uc_xgb.py -- do not edit manually.
// Platt sigmoid: blended ucScore (0-100) -> P(hit_uc_proxy)%
// PLACEHOLDER -- run scripts/train_uc_xgb.py to fit real coef from labeled data.
// Approximation grounded in observed tier precision:
//   score 36 -> ~33% | score 60 -> ~60% | score 80 -> ~77%

export const UC_PLATT_COEF      = 0.04;
export const UC_PLATT_INTERCEPT = -2.0;
export const UC_CALIBRATION_META = {
  coef:       UC_PLATT_COEF,
  intercept:  UC_PLATT_INTERCEPT,
  label:      'hit_uc_proxy (hit_t1 AND outcome_pct_20d > 12)',
  generated:  'placeholder',
  n_train:    0,
  val_brier:  null as number | null,
};

/**
 * Convert raw blended ucScore (0-100) to calibrated probability %.
 * Output is 0-100 integer representing P(hit_uc_proxy) in percent.
 */
export function calibrateUCScore(rawScore: number): number {
  const logit = UC_PLATT_COEF * rawScore + UC_PLATT_INTERCEPT;
  return Math.round(100 / (1 + Math.exp(-logit)));
}
