// AUTO-GENERATED by scripts/train_uc_xgb.py -- do not edit manually.
// Generated: 2026-08-07, n_train=3510, Brier=0.1244, AUC=0.6385
// Platt sigmoid: blended ucScore (0-100) -> P(hit_uc_proxy)%

export const UC_PLATT_COEF      = 0.033240;
export const UC_PLATT_INTERCEPT = -3.123537;
export const UC_CALIBRATION_META = {
  coef:       0.033240,
  intercept:  -3.123537,
  label:      'hit_uc_proxy (hit_t1 AND outcome_pct_20d > 12)',
  generated:  '2026-08-07',
  n_train:    3510,
  val_brier:  0.1244 as number | null,
};

/**
 * Convert raw blended ucScore (0-100) to calibrated probability %.
 * Output: 0-100 integer = P(hit_uc_proxy) in percent.
 */
export function calibrateUCScore(rawScore: number): number {
  const logit = UC_PLATT_COEF * rawScore + UC_PLATT_INTERCEPT;
  return Math.round(100 / (1 + Math.exp(-logit)));
}
