// Copyright (c) 2024–2026 Kasi Krishnaraja Paldurai. All Rights Reserved.
// Proprietary and confidential. Unauthorised use or distribution is prohibited.
// See LICENSE file in the project root for full licence terms.

/**
 * UC score formula weight constants.
 * Auto-generated by scripts/uc_precision_analysis.js — do not edit manually.
 * Generated: 2026-09-16 | source: logger_v4_backtest (10,697 labeled logger rows, AUC 0.8911) | n_labeled: 10697
 *
 * v4 logger backtest grid search (4000 trials, 2026-09-16):
 *   AUC v3→v4: 0.8036→0.8911 (+0.087 on logger). Prec@58: 1.1%→2.7% (2.5× gate tighter).
 *   Key changes: rsi2↓9 (d=-0.105 negative), closeLoc↓16, bodyPct↓3, upperWick↑8, volBonus↑16, volAccel↑12.
 *   zoneTight unchanged (0 logger rows); cl_trend/rsi2Vel unchanged (0 labeled positives in logged rows).
 *
 * After 30 trading days of logger data (≥2026-10-14), run:
 *   node scripts/uc_precision_analysis.js --apply
 * which recomputes Cohen's d per feature from live labeled events and
 * overwrites this file with data-driven weights, then redeploys.
 */

export const UC_SCORE_WEIGHTS = {
  generated:   '2026-09-16',
  source:      'logger_v4_backtest',
  n_labeled:   10697,

  // Continuous-feature max points — updated from v4 logger backtest (2026-09-16).
  // Cohen d (logger, n=10697, n_pos=90): RangeATR=0.719, VolPre5=0.553, CloseLoc=0.315,
  //   VolR20=0.151, RSI2=-0.105 (negative!), UpperWick=-0.086, BodyPct=-0.059
  // clTrend/rsi2Vel: 4,941 rows logged but 0 labeled positives — held at manual until positives arrive
  closeLoc_pts:      16,   // v4: 16 (was 22; d=0.315 moderate, rebalanced vs stronger features)
  rsi2_pts:           9,   // v4: 9 (was 16; d=-0.105 NEGATIVE — lower RSI = more UC hits, overweighted)
  clTrend_pts:       18,   // manual — no labeled positives in logged rows yet
  clTrend_neutral:    9,
  rsi2Vel_pts:       13,   // manual — no labeled positives in logged rows yet
  rsi2Vel_neutral:    6.5,
  rangeATR_pts:      11,   // v4: 11 (was 10; d=0.719 strongest continuous feature)
  bodyPct_pts:        3,   // v4: 3 (was 7; d=-0.059 near-zero, was overweighted)
  zoneTight_pts:      8,   // unchanged — 0 logger rows with zone_tightness, can't optimize
  zoneTight_neutral:  4,   // unchanged
  upperWick_pts:      8,   // v4: 8 (was 4; d=-0.086 negative = lower wick = better, doubled)
  upperWick_neutral:  3.5, // v4: 3.5 (was 2; raised proportionally)
  volAccel_pts:      12,   // v4: 12 (was 10; d=0.553 via vol_pre5 proxy, strong)
  volAccel_neutral:   5,

  // Step-function vol bonus — thresholds fixed, pts are what we scale
  volBonus_3x5:  16,   // v4: 16 (was 12; vol surge most reliable UC precursor)
  volBonus_2x:    6.5, // v4: 6.5 (was 5)
  volBonus_1x5:   2,   // unchanged

  // Categorical bonuses (not auto-scaled — ratios are empirical, not Cohen's d)
  nearBrkAPlus_pts:  5,
  nearBrkA_pts:      2.5,
  archVF_pts:        4,
  archMP_pts:        3,
  archCC_pts:        2,
  archOther_pts:     1,

  // Brain V2 feature set 2 — added 2026-08-12 (manual_v4, pending labeled backtest)
  // vol dry+surge: surge vs quiet accumulation period (not vs 20d avg) — detects operator pre-positioning
  volDrySurge_pts:    8,
  // weekly resonance: last-5d pseudo-weekly close_loc≥70 + body≥25 — institutional follow-through
  weeklyResonate_pts: 6,
  // psychological magnet: price within 3% below round-number ceiling + close_loc≥70 — spring release
  magnetFlag_pts:     4,

  // Candle morphology (k-means K=5, N=1000 labeled, outcome_pct_20d>15% as UC proxy, 2026-08-12)
  // Coiled Spring (body<25 AND wick<20): hammer/dragonfly — 34.6% UC-proxy vs 27% baseline (+7.6pp)
  // Intraday absorption: traded down, recovered to high, no upper shadow = no distribution overhead
  morphCoiledSpring_pts: 3,   // v4: 3 (was 5; grid reduced, consistent with bodyPct↓)
  // Gravestone (body<25 AND wick>35): doji/shooting star — 23.4% UC-proxy (-3.6pp below baseline)
  // Reinforces PRE_BREAKOUT quality gate; explicit penalty for cross-stage gravestone candles
  morphGravestone_penalty: 6, // v4: 6 (was 4; grid strengthened penalty)

  // Nifty 5d market regime multipliers (applied in page.tsx after formula blend)
  niftyBullMult:     1.10,    // Nifty 5d > +2%
  niftyNeutralMult:  1.00,
  niftyBearMult:     0.85,    // Nifty 5d < -2%
  niftyBullThreshold:  2,
  niftyBearThreshold: -2,
} as const;

export type UCScoreWeights = typeof UC_SCORE_WEIGHTS;
