// Copyright (c) 2024–2026 Kasi Krishnaraja Paldurai. All Rights Reserved.
// Proprietary and confidential. Unauthorised use or distribution is prohibited.
// See LICENSE file in the project root for full licence terms.

/**
 * UC score formula weight constants.
 * Auto-generated by scripts/uc_precision_analysis.js — do not edit manually.
 * Generated: 2026-08-08 | source: manual_v4 | n_labeled: 0
 *
 * After 30 trading days of logger data (≥2026-09-16), run:
 *   node scripts/uc_precision_analysis.js --apply
 * which recomputes Cohen's d per feature from live labeled events and
 * overwrites this file with data-driven weights, then redeploys.
 */

export const UC_SCORE_WEIGHTS = {
  generated:   '2026-08-08',
  source:      'manual_v4',
  n_labeled:   0,

  // Continuous-feature max points (lo/hi hard-coded inline in computeUCScore —
  // only the point budget is auto-updated so the feature ranges stay stable).
  closeLoc_pts:      22,
  rsi2_pts:          16,
  clTrend_pts:       18,
  clTrend_neutral:    9,
  rsi2Vel_pts:       13,
  rsi2Vel_neutral:    6.5,
  rangeATR_pts:       5,
  bodyPct_pts:        5,
  zoneTight_pts:      6,
  zoneTight_neutral:  3,
  volAccel_pts:       5,
  volAccel_neutral:   2.5,

  // Step-function vol bonus — thresholds fixed, pts are what we scale
  volBonus_3x5:  12,   // >= 3.5x or >= 3.0x vol
  volBonus_2x:    5,   // >= 2.0x vol
  volBonus_1x5:   2,   // >= 1.5x vol

  // Categorical bonuses (not auto-scaled — ratios are empirical, not Cohen's d)
  nearBrkAPlus_pts:  5,
  nearBrkA_pts:      2.5,
  archVF_pts:        4,
  archMP_pts:        3,
  archCC_pts:        2,
  archOther_pts:     1,

  // Nifty 5d market regime multipliers (applied in page.tsx after formula blend)
  niftyBullMult:     1.10,    // Nifty 5d > +2%
  niftyNeutralMult:  1.00,
  niftyBearMult:     0.85,    // Nifty 5d < -2%
  niftyBullThreshold:  2,
  niftyBearThreshold: -2,
} as const;

export type UCScoreWeights = typeof UC_SCORE_WEIGHTS;
