// Copyright (c) 2024–2026 Kasi Krishnaraja Paldurai. All Rights Reserved.
// Proprietary and confidential. Unauthorised use or distribution is prohibited.
// See LICENSE file in the project root for full licence terms.

/**
 * UC score formula weight constants.
 * Auto-generated by scripts/uc_precision_analysis.js — do not edit manually.
 * Generated: 2026-09-14 | source: live_v1+v3_backtest (15,525 labeled events, AUC 0.856) | n_labeled: 15525
 *
 * v3 backtest grid search (3000 trials, 2026-09-14):
 *   AUC v2→v3: 0.829→0.856 (+0.027). Prec@75%-recall: 89.5%→91.7%.
 *   Key changes: closeLoc↑22, bodyPct↑7, zoneTight↑8, upperWick continuous +4.
 *
 * After 30 trading days of logger data (≥2026-10-14), run:
 *   node scripts/uc_precision_analysis.js --apply
 * which recomputes Cohen's d per feature from live labeled events and
 * overwrites this file with data-driven weights, then redeploys.
 */

export const UC_SCORE_WEIGHTS = {
  generated:   '2026-09-14',
  source:      'live_v1+v3_backtest',
  n_labeled:   15525,

  // Continuous-feature max points — updated from live forward-labeled pbfb_uc_logger data.
  // Cohen d values (8 trading days, n=6381, n_pos=90 UC hits):
  //   VolPre5=1.21, RangeATR=1.05, VolR20=0.40, CloseLoc=0.20, BodyPct=0.07, RSI2=0.02
  //   clTrend/rsi2Vel not yet logged — kept at prior manual weights until data collected
  // v3 backtest (2026-09-14): closeLoc↑22, bodyPct↑7, zoneTight↑8, upperWick=4 (continuous)
  closeLoc_pts:      22,   // v3 backtest: 22 (was 20; d=0.20)
  rsi2_pts:          16,   // PBFB sweep 2026-08-28: F1@35 peaks at 16 — unchanged
  clTrend_pts:       18,   // d unknown (not logged) — held at manual_v4 until next cycle
  clTrend_neutral:    9,
  rsi2Vel_pts:       13,   // d unknown (not logged) — held at manual_v4 until next cycle
  rsi2Vel_neutral:    6.5,
  rangeATR_pts:      10,   // d=1.05 (massive) — kept at live_v1 value; overrides v3 grid (5)
  bodyPct_pts:        7,   // v3 backtest: 7 (was 5; d=0.07)
  zoneTight_pts:      8,   // v3 backtest: 8 (was 6; lower zone% = tighter coil = UC precursor)
  zoneTight_neutral:  4,   // neutral raised proportionally (was 3)
  upperWick_pts:      4,   // v3 backtest: NEW. Continuous: high wick→0, no wick→4. All stocks.
  upperWick_neutral:  2,   // neutral (no data) = half of max
  volAccel_pts:      10,   // d=1.21 (strongest feature) — UP from 5; vol surge vs D-5 base
  volAccel_neutral:   5,

  // Step-function vol bonus — thresholds fixed, pts are what we scale
  volBonus_3x5:  12,   // >= 3.5x or >= 3.0x vol (d=0.40 for VolR20, held)
  volBonus_2x:    5,   // >= 2.0x vol
  volBonus_1x5:   2,   // >= 1.5x vol

  // Categorical bonuses (not auto-scaled — ratios are empirical, not Cohen's d)
  nearBrkAPlus_pts:  5,
  nearBrkA_pts:      2.5,
  archVF_pts:        4,
  archMP_pts:        3,
  archCC_pts:        2,
  archOther_pts:     1,

  // Brain V2 feature set 2 — added 2026-08-12 (manual_v4, pending labeled backtest)
  // vol dry+surge: surge vs quiet accumulation period (not vs 20d avg) — detects operator pre-positioning
  volDrySurge_pts:    8,
  // weekly resonance: last-5d pseudo-weekly close_loc≥70 + body≥25 — institutional follow-through
  weeklyResonate_pts: 6,
  // psychological magnet: price within 3% below round-number ceiling + close_loc≥70 — spring release
  magnetFlag_pts:     4,

  // Candle morphology (k-means K=5, N=1000 labeled, outcome_pct_20d>15% as UC proxy, 2026-08-12)
  // Coiled Spring (body<25 AND wick<20): hammer/dragonfly — 34.6% UC-proxy vs 27% baseline (+7.6pp)
  // Intraday absorption: traded down, recovered to high, no upper shadow = no distribution overhead
  morphCoiledSpring_pts: 5,
  // Gravestone (body<25 AND wick>35): doji/shooting star — 23.4% UC-proxy (-3.6pp below baseline)
  // Reinforces PRE_BREAKOUT quality gate; explicit penalty for cross-stage gravestone candles
  morphGravestone_penalty: 4,

  // Nifty 5d market regime multipliers (applied in page.tsx after formula blend)
  niftyBullMult:     1.10,    // Nifty 5d > +2%
  niftyNeutralMult:  1.00,
  niftyBearMult:     0.85,    // Nifty 5d < -2%
  niftyBullThreshold:  2,
  niftyBearThreshold: -2,
} as const;

export type UCScoreWeights = typeof UC_SCORE_WEIGHTS;
