// AUTO-GENERATED by scripts/train_uc_xgb.py -- do not edit manually.
// Generated: placeholder -- run scripts/train_uc_xgb.py to populate
// Label: hit_uc_proxy = hit_t1 AND outcome_pct_20d > 12 (big fast move = UC-type event)
export const UC_XGB_MODEL_JSON: unknown = null;
