/**
 * XGBoost Phase-2 score inference — TypeScript tree walker.
 * Model weights are embedded via lib/xgbModelWeights.ts (auto-generated by
 * scripts/train_xgb_score.py). Falls back gracefully to null when no model
 * is available — callers should use ucScore as fallback.
 *
 * Zero runtime dependencies — pure TypeScript, runs client-side.
 */

import { XGB_MODEL_JSON } from './xgbModelWeights';

let _model: XgbModel | null = null;

// Auto-initialize from embedded weights on module load
if (XGB_MODEL_JSON) {
  _model = XGB_MODEL_JSON as XgbModel;
}

interface XgbNode {
  leaf?: number;
  split?: string;
  split_condition?: number;
  yes?: XgbNode;
  no?: XgbNode;
  missing?: XgbNode;
}

interface XgbModel {
  generated: string;
  n_train: number;
  test_auc: number;
  base_score: number;
  feature_names: string[];
  trees: XgbNode[];
}

function walkTree(node: XgbNode, features: Record<string, number>): number {
  if (node.leaf !== undefined) return node.leaf;
  const val = features[node.split!];
  const child = (val === undefined || val === null)
    ? node.missing!
    : val < node.split_condition!
      ? node.yes!
      : node.no!;
  return walkTree(child, features);
}

function sigmoidScore(rawSum: number, baseScore: number): number {
  // XGBoost outputs: sigmoid(base_score_logit + sum_of_leaf_values)
  const baseLogit = Math.log(baseScore / (1 - Math.max(0.001, Math.min(0.999, baseScore))));
  return 1 / (1 + Math.exp(-(baseLogit + rawSum)));
}

export function loadXgbModel(modelJson: unknown): void {
  _model = modelJson as XgbModel;
}

export interface XgbFeatures {
  vol_ratio_20?: number;
  close_loc?: number;
  body_pct?: number;
  rsi2?: number;
  range_atr?: number;
  zone_len?: number;
  zone_tightness?: number;
  vol_accel?: number;
  rsi2_velocity?: number;
  cl_trend?: number;
  near_breakout_tier_enc?: number;  // A+=2, A=1, B=0, none=-1
  archetype_enc?: number;            // categorical int from training
}

/**
 * Infer XGBoost hit_t1 probability (0-1).
 * Returns null when model is unavailable — caller should fall back to ucScore.
 */
export function inferXgbScore(features: XgbFeatures): number | null {
  if (!_model || !_model.trees || _model.trees.length === 0) return null;
  const featureMap = features as Record<string, number>;
  let rawSum = 0;
  for (const tree of _model.trees) {
    rawSum += walkTree(tree, featureMap);
  }
  return sigmoidScore(rawSum, _model.base_score);
}

export function getXgbModelMeta(): { generated: string; n_train: number; auc: number } | null {
  if (!_model) return null;
  return { generated: _model.generated, n_train: _model.n_train, auc: _model.test_auc };
}
