"""
Survival analysis — KaplanMeier + CoxPH per archetype.

Reads scripts/results/survival_times.csv (produced by compute_survival_times.py),
fits KM curves and a stratified CoxPH model, then overwrites lib/survivalCurves.ts
with static lookup tables for TypeScript consumption.

Usage:
    pip install lifelines pandas
    python scripts/run_survival_analysis.py

Output:
    scripts/results/survival_report.txt   — KM medians, log-rank p-values, Cox HRs
    lib/survivalCurves.ts                  — auto-generated TypeScript constants
"""

import pathlib, sys, io
from datetime import datetime

import pandas as pd

try:
    from lifelines import KaplanMeierFitter, CoxPHFitter  # type: ignore
    from lifelines.statistics import logrank_test  # type: ignore
except ImportError:
    print("[ERROR] lifelines not installed. Run: pip install lifelines")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
data_path = pathlib.Path(__file__).parent / "results" / "survival_times.csv"
if not data_path.exists():
    print(f"[ERROR] {data_path} not found. Run compute_survival_times.py first.")
    sys.exit(1)

df = pd.read_csv(data_path)
df["reached_5pct"] = df["reached_5pct"].astype(bool)
df["event_observed"] = df["reached_5pct"].astype(int)

print(f"[INFO] Loaded {len(df)} survival records, "
      f"{df['reached_5pct'].sum()} reached 5% target, "
      f"{(~df['reached_5pct']).sum()} censored")

ARCHETYPES = df["archetype_type"].dropna().unique().tolist()

# ---------------------------------------------------------------------------
# KM fit per archetype
# ---------------------------------------------------------------------------
km_results: dict[str, dict] = {}
report = io.StringIO()
report.write(f"Survival Analysis Report — {datetime.utcnow().strftime('%Y-%m-%d')}\n")
report.write("=" * 60 + "\n\n")

for arch in ARCHETYPES:
    sub = df[df["archetype_type"] == arch].dropna(subset=["days_to_5pct"])
    if len(sub) < 10:
        print(f"[WARN] {arch}: only {len(sub)} records — skipping")
        continue

    kmf = KaplanMeierFitter()
    kmf.fit(sub["days_to_5pct"], event_observed=sub["event_observed"], label=arch)
    median_days = kmf.median_survival_time_

    # P(reach 5% by day N)
    def km_at(d: int) -> float:
        try:
            sf = kmf.survival_function_at_times([d]).values[0]
            return round(1.0 - float(sf), 4)
        except Exception:
            return 0.0

    km_results[arch] = {
        "n":      int(len(sub)),
        "n_hit":  int(sub["event_observed"].sum()),
        "median": float(median_days) if not pd.isna(median_days) else 99,
        "d5":     km_at(5),
        "d10":    km_at(10),
        "d20":    km_at(20),
    }

    report.write(f"Archetype: {arch}  n={len(sub)}  hits={sub['event_observed'].sum()}\n")
    report.write(f"  KM median days-to-5%: {median_days:.1f}\n")
    report.write(f"  P(hit by day 5)={km_at(5):.3f}  day10={km_at(10):.3f}  day20={km_at(20):.3f}\n\n")

# ---------------------------------------------------------------------------
# CoxPH — archetype as covariate (if multiple archetypes present)
# ---------------------------------------------------------------------------
if len(ARCHETYPES) > 1:
    report.write("CoxPH — archetype hazard ratios (reference = CompressionCoil)\n")
    report.write("-" * 60 + "\n")
    cph_df = df.dropna(subset=["days_to_5pct", "archetype_type"]).copy()
    # One-hot encode archetypes
    arch_dummies = pd.get_dummies(cph_df["archetype_type"], drop_first=True, prefix="arch")
    cph_df = pd.concat([cph_df[["days_to_5pct", "event_observed"]], arch_dummies], axis=1)
    try:
        cph = CoxPHFitter()
        cph.fit(cph_df, duration_col="days_to_5pct", event_col="event_observed")
        report.write(cph.summary.to_string() + "\n\n")
    except Exception as e:
        report.write(f"CoxPH failed: {e}\n\n")

# ---------------------------------------------------------------------------
# Write report
# ---------------------------------------------------------------------------
out_dir = pathlib.Path(__file__).parent / "results"
report_path = out_dir / "survival_report.txt"
report_path.write_text(report.getvalue())
print(f"[OK] Report → {report_path}")
print(report.getvalue())

# ---------------------------------------------------------------------------
# Generate lib/survivalCurves.ts
# ---------------------------------------------------------------------------
ts_lines = [
    "// AUTO-GENERATED by scripts/run_survival_analysis.py — do not edit manually.",
    f"// Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
    "// Kaplan-Meier probabilities of reaching the +5% target by day N, per archetype.",
    "",
    "export interface SurvivalCurve {",
    "  n: number;     // sample size",
    "  n_hit: number; // events (reached 5%)",
    "  median: number; // KM median days-to-5pct",
    "  d5: number;     // P(hit by day 5)",
    "  d10: number;    // P(hit by day 10)",
    "  d20: number;    // P(hit by day 20)",
    "}",
    "",
    "export const SURVIVAL_CURVES: Record<string, SurvivalCurve> = {",
]

for arch, data in km_results.items():
    ts_lines.append(
        f"  {arch}: "
        f"{{ n: {data['n']}, n_hit: {data['n_hit']}, median: {data['median']:.1f}, "
        f"d5: {data['d5']}, d10: {data['d10']}, d20: {data['d20']} }},"
    )

ts_lines += ["};", ""]

ts_path = pathlib.Path(__file__).parent.parent / "lib" / "survivalCurves.ts"
ts_path.write_text("\n".join(ts_lines))
print(f"[OK] TypeScript constants → {ts_path}")
